version: '3.8'

networks: 
    localdev:
        name: localdev

services:
    customapitemplate:
        image: ${DOCKER_REGISTRY-}customapitemplate
        restart: always
        build:
            context: .
            dockerfile: CustomAPITemplate/Dockerfile
        depends_on:
            - db-server
            - redis
        networks:
            - localdev

    db-server:
        image: postgres
        container_name: postgres
        volumes:
            - postgres-data:/var/lib/postgresql
        environment:
            - POSTGRES_USER=customapitemplateuser
            - POSTGRES_PASSWORD=customapitemplatepasswords
            - POSTGRES_DB=customapitemplateexample
        ports:
            - "1400:5432"
        networks:
            - localdev

    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - localdev

volumes:
    postgres-data: