version: '3.8'

networks: 
    localdev:
        name: localdev
        driver: bridge

services:
    (DockerProjectName):
        image: ${DOCKER_REGISTRY-}(DockerProjectName)
        restart: always
        build:
            context: .
            dockerfile: CustomAPITemplate/Dockerfile
        depends_on:
#if (DatabaseProvider == "PostgreSQL")
            - postgres
#endif
#if (DatabaseProvider == "SqlServer")
            - mssql
#endif
#if (Cache == "Redis")
            - redis
#endif
#if (IsElasticSearchEnabled)
            - elastic-search
#endif
        networks:
            - localdev
        ports:
            - "5000:443"
            - "5001:80"
#if (DatabaseProvider == "PostgreSQL")
    postgres:
        image: postgres
        container_name: (DockerProjectName)-postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=Test123+
        ports:
            - "5432:5432"
        networks:
            - localdev
#endif

#if (DatabaseProvider == "SqlServer")          
    mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: (DockerProjectName)-mssql
        volumes:
            - mssql:/var/opt/mssql
        environment:
            - SA_PASSWORD=Test123+
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
        networks:
            - localdev
#endif

#if (Cache == "Redis")
    redis:
        image: redis
        container_name: (DockerProjectName)-redis
        volumes:
            - redis:/data
        ports:
            - "6379:6379"
        networks:
            - localdev
#endif
#if (IsElasticSearchEnabled)
    elastic-search:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
        container_name: (DockerProjectName)-elasticsearch
        volumes:
            - elastic-search:/usr/share/elasticsearch/data
        environment:
            - node.name=elastic-search
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_POTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
        networks:
            - localdev
            
    kibana:
        image: docker.elastic.co/kibana/kibana:8.6.2
        container_name: (DockerProjectName)-kibana
        ports:
            - 5601:5601
        environment:
            - ELASTICSEARCH_URL=http://elastic-search:9200
            - ELASTICSEARCH_HOSTS=http://elastic-search:9200
            - xpack.security.enabled=false
        networks:
            - localdev
#endif
volumes:
#if (DatabaseProvider == "PostgreSQL")
    postgres:
        name: (DockerProjectName)-postgres
#endif
#if (DatabaseProvider == "SqlServer")
    mssql:
        name: (DockerProjectName)-mssql
#endif
#if (Cache == "Redis")
    redis:
        name: (DockerProjectName)-redis
#endif
#if (IsElasticSearchEnabled)
    elastic-search:
        name: (DockerProjectName)-elastic-search
#endif